### ISSUE TITLE
Fix redirect issue for PC browsers

### ISSUE THREAD

**Issue by papko26** [papko26/google-link-to-waze#2]
![image](https://github.com/user-attachments/assets/f7748b8f-272b-4b32-b5c6-9b2357ee8ac0)
![image](https://github.com/user-attachments/assets/ddb93b08-6fc3-46e6-b3f7-7f8df1791ab8)
![image](https://github.com/user-attachments/assets/70956b78-68ef-4c85-842d-9bbc57ea72c6)

**Comment by papko26** [comment]
Chrome Version 131.0.6778.69 (Official Build) (64-bit), No AdBlock

**Comment by papko26** [comment]
Fixed in 
[05972d5](https://github.com/papko26/google-link-to-waze/commit/05972d5f8df1ea3a8e72ed5207baf98b916351be)

**Comment by DmGoncharov** [comment]
Проблема - при отправке линка для Гугл мапс в Вейз, в нем открывается лишь последний пункт из маршрута, в котором 5 и более пунктов следования.
